version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Setup Env
          command: |
            echo 'export IMAGE_USERNAME=eddywashere' >> $BASH_ENV 
            echo 'export IMAGE_NAME=ci' >> $BASH_ENV
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Tag & Push Docker image
          command: |
            docker build -t $IMAGE_NAME:$CIRCLE_SHA1 .
            docker tag $IMAGE_NAME:$CIRCLE_SHA1 $IMAGE_USERNAME/$IMAGE_NAME:$CIRCLE_SHA1
            docker tag $IMAGE_NAME:$CIRCLE_SHA1 $IMAGE_USERNAME/$IMAGE_NAME:latest
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $IMAGE_USERNAME/$IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_USERNAME/$IMAGE_NAME:latest
            echo $CIRCLE_SHA1
